package com.ecommerce.microcommerce.web.controller;

import com.ecommerce.microcommerce.accessingdatamysql.PersonnageRepository;
import com.ecommerce.microcommerce.model.Personnage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PersonnageRepository personnageRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewPersonnage (@RequestParam String name
            , @RequestParam String classe) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Personnage n = new Personnage();
        n.setName(name);
        n.setClasse(classe);
        personnageRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Personnage> getAllPersonnages() {
        // This returns a JSON or XML with the users
        return personnageRepository.findAll();
    }
}
